### ISSUE TITLE
Support options for filename out and STDOUT

### ISSUE THREAD

**Issue by rbuckland** [javanile/yamlinc#2]
Currently the `yamlinc` generates a `<file>.inc.yml` file in the current directory. 
Greater flexibility is needed where the output file can be specified. 

For example 

`yamlinc -o some/path/to/MyType.yml src/types/MyType.yml`

or 
Writing to STDOUT
`yamlinc -o -  src/types/MyType.yml`

**Comment by francescobianco** [comment]
Hi @rbuckland  a new version 0.1.0 is on NPM registry
https://www.npmjs.com/package/yamlinc
with: Support for STDOUT

please help, support Yamlinc:

promote Yamlinc into your team and your community
ask your friends to click on Star button
share your Yaml file scenarios (es. Drupal, Symfony, API, Configurations, Infrastructure as code, etc..)

**Comment by jahluwalia** [comment]
The latest 0.1.0 on npm doesn't seem to work:

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/yamlinc/src/yamlinc.js:9:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by francescobianco** [comment]
Hi @jahluwalia @rbuckland please use version 0.1.1
